version: '3.8'
services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    environment:
      FLASK_APP: app.py  # Esto podría variar según cómo configure tu aplicación Flask
  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m unittest test_app.py
    depends_on:
      - flask_app
